### ISSUE TITLE
Log and error :  bye, log, error

### ISSUE THREAD

**Issue by jadenjack** [the-boyj/signaling-server#7]
EVENT_BYE ="bye" : 통화 종료

EVENT_LOG = "log" : 로그

EVENT_SERVER_ERROR = "server_error" : 서버가 (브로드캐스팅) 에러 전송 //서버가 catch한 에러 (description은 json으로 전달)

EVENT_PEER_ERROR : "peer_error" : 피어가 서버에게 에러 전송 //피어가 catch한 에러 (description은 json으로 전달)

**Comment by shooes270** [comment]
What is the purpose of ```log```?
We need more detail explanation plz.
