### ISSUE TITLE
로깅 라이브러리 적용

### ISSUE THREAD

**Issue by shooes270** [the-boyj/signaling-server#72]
**Description**
여러 시그널링 이벤트 핸들링에 대하여 콘솔 출력을 통해 로깅을 해왔습니다.
리다이렉션을 통해 이러한 로그를 수집할 수 있었지만 로그의 수준(Level)에 따른 수집이 불가능했습니다.
이에 적절한 로깅 라이브러리 사용이 필요해보입니다.
[링크](https://github.com/sindresorhus/awesome-nodejs#logging)를 참고하여 적절한 로그 라이브러리를 선택하면 좋을 것 같습니다.

**As Is**
Console.log를 이용한 로깅
로그 수준에 따른 분류 불가능

**To Be**
특정 로깅 라이브러리를 통한 로깅
개발단계, 프로덕션 단계에 맞게 적절한 로그 수준 조절 및 수집 가능

**Comment by jadenjack** [comment]
수집된 로그는 어디에 저장되는건가요?

**Comment by shooes270** [comment]
@jadenjack 
당장은 개발 단계에서의 (비)정상 사용을 확인하기 위한 용도로 사용될것입니다.
이후 필요하다면 Redis, Logstash, Elastic Search를 이용한 로그 수집 및 분석 아키텍처를 고려할수있습니다.

**Comment by shooes270** [comment]
create feature branch based on develop
[compare with master](https://github.com/the-boyj/signaling-server/compare/feature/072-logging-library)
